# Generated by Django 3.2.3 on 2021-07-03 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
    ]
