# Generated by Django 3.2.3 on 2021-07-03 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_question_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
    ]
